// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvjW8-4pmKG2QJ1RMdF9fMDmIq5ITFU4',
    appId: '1:919981147756:android:05a71bf031f479446d3a49',
    messagingSenderId: '919981147756',
    projectId: 'multi-29b4d',
    storageBucket: 'multi-29b4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYciGvPFKSTWlv-aL4X0XdLAktbl11XbY',
    appId: '1:919981147756:ios:abfe9bdd4e9de52f6d3a49',
    messagingSenderId: '919981147756',
    projectId: 'multi-29b4d',
    storageBucket: 'multi-29b4d.firebasestorage.app',
    androidClientId: '919981147756-ndpe9o667frus8ift7pr7219ii5a4ml7.apps.googleusercontent.com',
    iosClientId: '919981147756-ph485u22h0il48mfivspcl8sdcrfggio.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStoreApp',
  );
}
